---
- name: Install Multipath Device Mapper
  ansible.builtin.dnf:
    name: device-mapper-multipath
    state: present

- name: Configure Multipath
  ansible.builtin.template:
    src: etc/multipath.conf.j2
    dest: /etc/multipath.conf
  notify: reload multipathd

- name: Ensure Multipathd is running and enabled
  ansible.builtin.systemd_service:
    name: multipathd
    enabled: true
    state: started
...
